Repository irojkov-ph/epic_demics, pull requests merged in 2019-11, with the labels that each got.

#17 New/tests
  logs/displacements.txt
  src/count_nearest_neighbours.m
  src/density_ill.m
  src/displacement.m
  src/evolution_illness.m
  src/evolve_cell.m
  src/step.m
  src/switch_cells.m
  src/system_init.m
  src/update_ages.m
  tests/general_test.m
  tests/test_functions/count_nearest_neighbours_test.m
  tests/test_functions/density_ill_test.m
  tests/test_functions/displacement_test.m
  tests/test_functions/evolution_illness_test.m
  tests/test_functions/evolve_cell_test.m
  tests/test_functions/step_test.m
  tests/test_functions/switch_cells_test.m
  tests/test_functions/system_init_test.m
  tests/test_functions/update_ages_test.m
Labels: enhancement

#20 Creating evolution_vaccination.m
  .gitignore
  logs/displacements.txt
  src/draw.m
  src/evolution_vaccination.m
  src/evolve_cell.m
  tests/evolution_vacc.m
  tests/general_test.m
  tests/graphics_test.m
  tests/test_functions/count_nearest_neighbours_test.m
  tests/test_functions/density_ill_test.m
  tests/test_functions/displacement_test.m
  tests/test_functions/evolution_illness_test.m
  tests/test_functions/evolve_cell_test.m
  tests/test_functions/step_test.m
  tests/test_functions/switch_cells_test.m
  tests/test_functions/system_init_test.m
  tests/test_functions/update_ages_test.m
Labels: enhancement

#22 Nic simul
  logs/displacements.txt
  src/draw.m
  src/evolution_vaccination.m
  src/evolve_cell.m
  src/evolve_system.m
  src/main.m
  src/new_season.m
  src/system_init.m
  tests/general_test.m
Labels: enhancement, first to be merged

#28 Many small changes
  src/beta_influenza.m
  src/draw.m
  src/evolution_vaccination.m
  src/evolve_cell.m
  src/evolve_system.m
  src/main.m
  tests/general_test.m
Labels: bug, small changes

#30 Many changes
  .gitignore
  data/swiss_influenza_2017-2018_2018-2019.mat
  data/swiss_mortality_data_2016-2018(2).mat
  data/swiss_mortality_data_2016-2018(3).mat
  data/swiss_mortality_data_2016-2018.mat
  logs/displacements.txt
  main.m
  src/beta_influenza.m
  src/compare_config.m
  src/draw.m
  src/evolution_vaccination.m
  src/evolve_cell.m
  src/evolve_system.m
  src/main.m
  src/mu_age.m
  src/start.m
  src/step.m
  src/system_init.m
  src/update_ages.m
  src/update_betas.m
Labels: enhancement
